dataset_root: data/hpatches-sequences-release
dataset_output_dir: data/dataset

splits:
  train: 300000
  valid: 10000
  test: 10000

patch_size: 40
grid_spacing: 20

model:
  input_shape: [40, 40, 1]
  embedding_dim: 64
  margin: 0.5
  decision_threshold: 0.4

training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001

dataset:
  train: data/dataset/train_dataset.npz
  valid: data/dataset/valid_dataset.npz

model_output_dir: model_outputs/
