dataset_root: data/hpatches-sequences-release
dataset_output_dir: data/dataset

splits:
  train: 500000
  valid: 20000
  test: 20000

patch_size: 40
grid_spacing: 20

use_ssim_filter: true
ssim_threshold: 0.5

model:
  input_shape: [40, 40, 1]
  embedding_dim: 128
  margin: 0.5

training:
  epochs: 50
  batch_size: 64
  learning_rate: 0.001

dataset:
  train: data/dataset/train_dataset.npz
  valid: data/dataset/valid_dataset.npz

model_output_dir: model_outputs/

resume_training: true

onnx:
  export_enabled: true
  quantize: true
  checkpoint_path: model_outputs/checkpoints/epoch_22.pt
  output_onnx: model_outputs/patchmatch_model.onnx
  output_quant_onnx: model_outputs/patchmatch_model_quant.onnx
